version: "3.2"

services:
  # Radarr - https://hotio.dev/containers/radarr
  # <mkdir /volume1/docker/radarr>
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: bridge
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_CONFIG_DIR}/radarr:/config:rw
      - ${DOCKER_STORAGE_DIR}:/data:rw
      - ${MOVIES_DIR}:/data/media:rw

  # Sonarr - https://hotio.dev/containers/sonarr
  # <mkdir /volume1/docker/sonarr>
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: bridge
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_CONFIG_DIR}/sonarr:/config:rw
      - ${DOCKER_STORAGE_DIR}:/data:rw
      - ${TV_DIR}:/data/media:rw

  # Lidarr - https://hotio.dev/containers/lidarr
  # <mkdir /volume1/docker/lidarr>
  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: bridge
    ports:
      - 8686:8686
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_CONFIG_DIR}/lidarr:/config:rw
      - ${DOCKER_STORAGE_DIR}:/data:rw
      - ${MUSIC_DIR}:/data/media:rw

  # Bazarr - https://hotio.dev/containers/bazarr
  # <mkdir /volume1/docker/bazarr>
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: bridge
    ports:
      - 6767:6767
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_CONFIG_DIR}/bazarr:/config:rw
      - ${MOVIES_DIR}:/data/media/movies:rw
      - ${TV_DIR}:/data/media/tv:rw

  # Deluge - https://github.com/linuxserver/docker-deluge
  # <mkdir /volume1/docker/deluge>
  deluge:
    container_name: deluge
    image: ghcr.io/linuxserver/deluge:latest
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: service:wireguard
    depends_on:
      - wireguard
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=022
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_CONFIG_DIR}/deluge:/config:rw
      - ${DOCKER_STORAGE_DIR}/torrents:/data/torrents:rw

  # Jackett - https://github.com/linuxserver/docker-jackett
  # <mkdir /volume1/docker/jackett>
  jackett:
    container_name: jackett
    image: ghcr.io/linuxserver/jackett:latest
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: service:wireguard
    depends_on:
      - wireguard
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
      - AUTO_UPDATE=false
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_CONFIG_DIR}/jackett:/config:rw

  # Calibre - https://hub.docker.com/r/linuxserver/calibre
  # <mkdir /volume1/Books>
  calibre:
    container_name: calibre
    image: ghcr.io/linuxserver/calibre
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: bridge
    ports:
      - 8500:8080
      - 8501:8081
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BOOKS_DIR}:/config

  # NZBHydra2 - https://hotio.dev/containers/nzbhydra2
  # <mkdir /volume1/docker/nzbhydra2>
  nzbhydra2:
    container_name: nzbhydra2
    image: ghcr.io/linuxserver/nzbhydra2:latest
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: bridge
    ports:
      - 5076:5076
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_CONFIG_DIR}/nzbhydra2:/config:rw
      - ${DOCKER_STORAGE_DIR}:/downloads:rw

  # Wireguard - https://hub.docker.com/r/linuxserver/wireguard
  # <mkdir /volume1/docker/wireguard>
  wireguard:
    container_name: wireguard
    image: jordanpotter/wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv4.conf.all.rp_filter: 2
    devices:
      - /dev/net/tun
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - INTERNAL_SUBNET=192.168.1.0/24
    volumes:
      - ${DOCKER_CONFIG_DIR}/wireguard:/config
    ports:
      - 8112:8112 # deluge
      - 6881:6881 # deluge
      - 6881:6881/udp # deluge
      - 58846:58846 # deluge
      - 9117:9117 # jackett

  # Calibre Web - https://hub.docker.com/r/linuxserver/calibre-web
  # <mkdir /volume1/docker/calibre-web>
  calibre_web:
    container_name: calibre_web
    image: ghcr.io/linuxserver/calibre-web
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    ports:
      - 8083:8083
    volumes:
      - ${DOCKER_CONFIG_DIR}/calibre-web:/config:rw
      - "${BOOKS_DIR}/Calibre\ Library:/books:rw"

  # Homarr - https://github.com/ajnart/homarr
  # <mkdir /volume1/docker/homarr>
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_CONFIG_DIR}/homarr/configs:/app/data/configs
      - ${DOCKER_CONFIG_DIR}/homarr/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 7575:7575

  # Readarr - https://hub.docker.com/r/linuxserver/readarr
  # <mkdir /volume1/docker/readarr>
  readarr:
    container_name: readarr
    image: lscr.io/linuxserver/readarr:develop
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_CONFIG_DIR}/readarr:/config
      - "${BOOKS_DIR}/Calibre\ Library:/books:rw"
      - ${DOCKER_STORAGE_DIR}/torrents:/data/torrents:rw
    ports:
      - 8787:8787
